#!/bin/bash

stime=1m
[ -z $1 ] || stime=$1

while [ 1 ]
do
    ping -c1 -w1 1.1.1.1 >/dev/null
	if [[ $? -eq 1 ]]; then
		caa -s && caa -d && notify-send "Sophos" "Reconnected"
	fi
	sleep $stime # Time Between Succescive Checks
	# echo "looped $state"
done
